spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/DevBlog?createDatabaseIfNotExist=true
spring.datasource.username: root
spring.datasource.password: kol97szc
spring:
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false

spring.mail.host: smtp.mailtrap.io
spring.mail.username: 7deeb8027c6148
spring.mail.password: 4f4a0cf4d2e697
spring.mail.port: 2525
mail.debug: true

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#      enabled: true

#spring.mandatory-file-encoding=UTF-8
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 111-11-11
  email: mail@mail.ru"
  copyright: <Буратино Карлович>
  copyrightFrom: 2005
#spring.jpa.properties.hibernate.validator.apply_to_ddl=false


