drop table if exists captcha_codes;
drop table if exists global_settings;
drop table if exists post;
drop table if exists post_comments;
drop table if exists post_votes;
drop table if exists tag;
drop table if exists tags2post;
drop table if exists user;
create table captcha_codes (id integer not null auto_increment, code tinytext not null, secret_code tinytext not null, time datetime not null, primary key (id)) engine=MyISAM;
create table global_settings (id integer not null auto_increment, code varchar(255) not null, name varchar(255) not null, value varchar(255) not null, primary key (id)) engine=MyISAM;
create table post (id integer not null auto_increment, is_active tinyint(1) not null, moderation_status enum('NEW','ACCEPTED','DECLINED') default 'NEW' not null, text text not null, time datetime not null, title varchar(255) not null, view_count int not null, moderator_id int NOT NULL COMMENT 'id пользователя', user_id int NOT NULL COMMENT 'id пользователя' not null, primary key (id)) engine=MyISAM;
create table post_comments (id integer not null auto_increment, parent_id integer, text text not null, time datetime not null, post_id integer not null, user_id int NOT NULL COMMENT 'id пользователя' not null, primary key (id)) engine=MyISAM;
create table post_votes (id integer not null auto_increment, time datetime not null, value tinyint(1) not null, post_id integer not null, user_id int NOT NULL COMMENT 'id пользователя' not null, primary key (id)) engine=MyISAM;
create table tag (id integer not null auto_increment, name varchar(255) not null, primary key (id)) engine=MyISAM;
create table tags2post (id integer not null auto_increment, post_id integer not null, tag_id integer not null, primary key (id)) engine=MyISAM;
create table user (id int NOT NULL COMMENT 'id пользователя' not null auto_increment, code varchar(255) NOT NULL COMMENT 'код для восстановления пароля', email varchar(255) NOT NULL COMMENT 'e-mail пользователя' not null, is_moderator tinyint NOT NULL COMMENT 'является ли пользователь модератором (может ли править глобальные настройки сайта и модерировать посты)' not null, name varchar(255) NOT NULL COMMENT 'имя пользователя' not null, password varchar(255) NOT NULL COMMENT 'хэш пароля пользователя' not null, photo text NOT NULL COMMENT 'ссылка на фотографию', reg_time datetime NOT NULL COMMENT 'дата и время регистрации пользователя' not null, primary key (id)) engine=MyISAM;
alter table post add constraint FKalqf2lcs0khgmu1b8gp0lnn8v foreign key (moderator_id) references user (id);
alter table post add constraint FK72mt33dhhs48hf9gcqrq4fxte foreign key (user_id) references user (id);
alter table post_comments add constraint FKmws3vvhl5o4t7r7sajiqpfe0b foreign key (post_id) references post (id);
alter table post_comments add constraint FKbi7tx0kp7t1pgugyfidm7o00d foreign key (user_id) references user (id);
alter table post_votes add constraint FKkii0lkyj3a3jj95vgym33ho4b foreign key (post_id) references post (id);
alter table post_votes add constraint FKd9rqv0g3hsf0p1bbgre7qjhej foreign key (user_id) references user (id);
alter table tags2post add constraint FKestau6o3scken6t9bn9nxe5sj foreign key (post_id) references post (id);
alter table tags2post add constraint FKc2wuynap0t499wfjega1pts7q foreign key (tag_id) references tag (id);